### ISSUE TITLE
Line breaks

### ISSUE THREAD

**Issue by Sat32blk** [gugutab/TvOverlay#14]
Is there a way to have line breaks in messages sent from home assistant?

**Comment by gugutab** [comment]
You can edit your Script or Automation in yaml mode like this examples:

```
service: notify.yourdevice
data:
  message: |
    line1
    line2

```

or

```
service: notify.yourdevice
data:
  message: |
    line1
    line2
```

On UI mode, I dont think it's possible. :(

**Comment by gugutab** [comment]
You can edit your Script or Automation in yaml mode like this examples:

```
service: notify.yourdevice
data:
  message: |
    line1
    line2

```

or

```
service: notify.yourdevice
data:
  message: |
    line1
    line2
```

On UI mode, I dont think it's possible. :(
