### ISSUE TITLE
Feature Request: Option to display current resolution and refresh rate on the Android TV overlay 

### ISSUE THREAD

**Issue by dineshalphaque** [gugutab/TvOverlay#24]
Title says it all. Would love a simple option for the app to display current resolution and refresh rate below the clock. This option can be turned on or off in the TV Overlay Remote app.

This would greatly help increase the app's usefulness. I'd presume these current values of the tv resolution and refresh rate can be read from Android.

**Comment by gugutab** [comment]
I experimented with the available APIs to retrieve screen information on Android TV, but the results were not very useful, as the values did not update based on content changes (such as changing the quality on any streaming apps).

For now, I will be closing this until new methods for obtaining and monitoring these values on Android TV are proposed.

Thanks.

**Comment by dineshalphaque** [comment]
Thanks for the effort and the attempt. I did ask around on some other forums, and these two APIs came back as suggestions, including registering for refresh rate and resolution change notifications.

Wonder if they would help?

1. https://developer.android.com/reference/kotlin/androidx/core/view/DisplayCompat
2. https://developer.android.com/media/optimize/performance/frame-rate

Once again, thanx so much for looking into this.

**Comment by gugutab** [comment]
Yeah, that's the one I tried.
The outputs is:
![image](https://github.com/user-attachments/assets/9799f2ab-3488-4ee9-a205-a6158f51bd97)
fixed all the time. And thats not even the correct resolution.
