### ISSUE TITLE
Project abandoned?

### ISSUE THREAD

**Issue by mickeynygaard** [gugutab/TvOverlay#36]
Hi.

Came across this project when trying to get some HA > Android TV notifications to work.
I see a bunch of posts with issues getting video to work and various other stuff, and no updates for ~10 months.

Has the project been abandoned or is it still in active development?

**Comment by gugutab** [comment]
Hi!
The project is not abandoned! An update is currently in the works, though progress is happening at a slower pace. Thank you for your patience and continued support—stay tuned for future updates!
