### ISSUE TITLE
Where is the TvOverlay Remote app?

### ISSUE THREAD

**Issue by Uberseer** [gugutab/TvOverlay#37]
I just installed the app on my Android TV (Nvidia Shield) and am trying to find the companion app for my phone.  The QR code onscreen does not work (no such app), and my search of the play store doesn't show it either.

Can someone provide a link or help finding the companion app?

**Comment by gugutab** [comment]
The app "TvOverlay Remote" was removed from the Play Store by Google, and the exact reason for this is not clear at the moment. I am actively working on restoring the app. In the meantime, you can download a beta version of the remote app [here](https://github.com/gugutab/TvOverlay/tree/main/apk), but please note that the premium purchase feature will not be functional.

**Comment by gugutab** [comment]
🎉 **TvOverlay Remote is Back on Play Store** 🎉

Google just accepted my appeal with no changes to the app.
