### ISSUE TITLE
ReST API details

### ISSUE THREAD

**Issue by Uberseer** [gugutab/TvOverlay#38]
I want to send messages to my TvOverlay app using ReST from a phone system, to indicate incoming calls.

Can someone explain the API syntax, and perhaps some examples?

**Comment by Uberseer** [comment]
After some experimenting:

curl -X POST http://{host}:{port}/notify \
     -H "Content-Type: application/json" \
     -d '{
           "title": "Hello World",
           "message": "This is a test notification",
           "icon": "http://example.com/icon.png"
         }'

Seems to work.  But would love if someone documented the various parameters and URI's

**Comment by Uberseer** [comment]
I can't figure out how to remove the "RestAPI" appearing on screen in the app title.  Anyone know how to get rid of that?

**Comment by gugutab** [comment]
> I can't figure out how to remove the "RestAPI" appearing on screen in the app title. Anyone know how to get rid of that?

Currently not possible, but that will change soon: https://github.com/gugutab/TvOverlay/issues/33
