### ISSUE TITLE
Closing a notification with API/MQTT

### ISSUE THREAD

**Issue by dmakovec** [gugutab/TvOverlay#44]
I have a notification configured for doorbell video when somebody comes to my door, and by default it stays up for 3 minutes to give me time to get to the TV.

Is there any way via API or MQTT I can request this notification be closed, once I've opened the door and don't need the notification on screen any more?

**Comment by hastime** [comment]
Hi,

So to close a notification using Home Assistant service call I am doing the following: 

action: notify.tvoverlaynotify
data:
  message: " "
  data:
     id: cam
     seconds: 0

The important thing to do is to send the same ID for 0 seconds and this will clear the notification, not sure if this works with MQTT but should be the same on the API. 

Hope it helps!

**Comment by hastime** [comment]
just a follow up thought, if you have a door sensor you could create a Home Assistant automation to send the O second notification with the same ID as a the original notification and it will then close as soon as the door is opened.

**Comment by dmakovec** [comment]
This is excellent, thanks for this! I suspected it would be something to do with re-using ID, but replacing with the blank message and zero second timeout didn't occur to me. Thanks @hastime ! :)

**Comment by hastime** [comment]
You're welcome, glad it helped!

**Comment by gugutab** [comment]
Thanks for the help @hastime!
I'm probably gonna add something like the visible parameter of Fixed notifications in the future to have a better way to dismiss the notifications.

**Comment by hastime** [comment]
@gugutab - Having a visible parameter would be useful for the non-fixed notifications, happy to help with this or carry out testing if needed. Thanks for the work on an awesome tool!
