### ISSUE TITLE
Google TV Streamer - will not open properly 

### ISSUE THREAD

**Issue by bdavis313** [gugutab/TvOverlay#45]
Upon an initial install, the setup screen will briefly pop-up, and then close.  Subsequently trying to reopen the app does nothing.  The open screen is just static

**Comment by gugutab** [comment]
Hey! I've released a new version (1.0.4) of the app with support for Android 14, and it's now available for testing.

You can join our testing program here: https://play.google.com/apps/testing/com.tabdeveloper.tvoverlay

Feel free to reach out if you encounter any issues
