### ISSUE TITLE
Setup issues

### ISSUE THREAD

**Issue by ola-tunji** [gugutab/TvOverlay#8]
Hello,

I’ve had this integrated for a while and I’ve been trying to figure out why I don’t have the notify service (notify.tvoverlaysuite) showing up in home assistant. Is there something wrong in my setup?

home assistant version: 2023.10.5

**Comment by ola-tunji** [comment]
Is this what needs to be setup in order to be able to have the correct notify service: home_assistant/configuration_sample.yaml

**Comment by gugutab** [comment]
Hey @ola-tunji !
"tvoverlaysuite" is actually the name of my device and was in a sample by mistake. I just changed it to "tvoverlaysample" . Please, check if the name in your configuration.yaml is  tvoverlaysuite, tvoverlaysample or something else. Also be sure to restart your home assistant after adding or updating a notification to your configuration.yalm.

Please let me know if you got it working and, if not, include the configuration.yaml code with the tvoverlay.
